package programa.controlador;

public enum Evento {
    JUGADA_ARMADA,
    CAMBIO_DE_JUGADOR,
    MANO_ACTUALIZADA,
    LISTO_PARA_JUGAR,
    POZO_ACTUALIZADO,
    JUGADA_RECHAZADA,
    JUGADOR_BAJO,
    BAJADA_RECHAZADA,
    JUGADA_MODIFICADA,
    DESCARGA_RECHAZADA,
    RONDA_GANADA,
    JUGADOR_AGREGADO,
}
